import {
  Brain as Anxiety,
  Sparkles as Self,
  HeartPulse as Pain,
  Moon as Sleep,
  Heart as Emotional,
  ShieldAlert as Fear,
  BrainCircuit as Overthinking,
  Cigarette as Smoking,
  Activity as Stress,
  Scale as Weight,
} from 'lucide-react'

export const CATEGORIES = [
  {
    id: 'Anxiety Relief / चिंता से राहत',
    name: 'Anxiety Relief / चिंता से राहत',
    description: ' ',
    icon: Anxiety,
    color: 'from-blue-500 to-cyan-400',
    image: '/images/categories/anxiety-relief.png',
    video: 'https://www.w3schools.com/html/mov_bbb.mp4',
     
    itemCount: 24,
    items: [
      { id: 't1', title: 'Session-1', description: 'गहन विश्राम और अंतरिक्ष सहजता का हिप्नोथेरेपी  सेशन', tokenCost: 2, free: false, audioEn: 'https://www.soundjay.com/buttons/sounds/button-1.mp3', audioHi: 'https://res.cloudinary.com/dtlitc3nv/video/upload/v1782919318/relax_s1_ziryk9.mp3', image: '/images/content/anxiety/anxiety 1.jpg' },
      { id: 't2', title: 'Session-2', description: 'HTML, CSS, and JavaScript from scratch.', tokenCost: 2, free: false, audioEn: 'https://www.soundjay.com/buttons/sounds/button-1.mp3', audioHi: 'https://www.soundjay.com/buttons/sounds/button-1.mp3', image: '/images/content/anxiety/anxiety2.jpg' },
      { id: 't3', title: 'Session-3', description: 'Build scalable systems on AWS and GCP.', tokenCost: 2, free: false, audioEn: 'https://www.soundjay.com/buttons/sounds/button-1.mp3', audioHi: 'https://www.soundjay.com/buttons/sounds/button-1.mp3', image: '/images/content/anxiety/anxiety3.jpg' },
    ],
  },
  {
    id: 'Overthinking Control / ज़्यादा सोचने की आदत पर नियंत्रण',
    name: 'Overthinking Control / ज़्यादा सोचने की आदत पर नियंत्रण',
    description: ' ',
    icon: Overthinking,
    color: 'from-indigo-500 to-purple-400',
    image: '/images/categories/overthinking-control.png',
    video: 'https://www.w3schools.com/html/mov_bbb.mp4',
    itemCount: 19,
    items: [
      { id: 'd1', title: 'Session-1', description: 'आंतरिक शांति और चिंता रहित रहने के लिए', tokenCost: 2, free: false, audioEn: 'https://www.soundjay.com/buttons/sounds/button-1.mp3', audioHi: 'https://res.cloudinary.com/dtlitc3nv/video/upload/v1782918954/overthinking_1_qw6nhl.mp3', image: '/images/content/overthinking/overthinking 1.jpg' },
      { id: 'd2', title: 'Session-2', description: 'शून्य से शून्य की ओर', tokenCost: 2, free: false, audioEn: 'https://www.soundjay.com/buttons/sounds/button-1.mp3', audioHi: 'https://res.cloudinary.com/dtlitc3nv/video/upload/v1783328382/overthinking_2_gzqt2c.mp3', image: '/images/content/overthinking/overthinking 2.jpg' },
      { id: 'd3', title: 'Session-3', description: 'Intro to animation in After Effects.', tokenCost: 2, free: false, audioEn: 'https://www.soundjay.com/buttons/sounds/button-1.mp3', audioHi: 'https://www.soundjay.com/buttons/sounds/button-1.mp3', image: '/images/content/overthinking/overthinking 3.jpg' },
    ],
  },
  {
    id: 'Pain Management / दर्द का प्रबंधन',
    name: 'Pain Management / दर्द का प्रबंधन',
    description: ' ',
    icon: Pain,
    color: 'from-yellow-500 to-orange-400',
    image: '/images/categories/pain-management.png',
    video: 'https://www.w3schools.com/html/mov_bbb.mp4',
    itemCount: 31,
    items: [
      { id: 'f1', title: 'Session-1 ', description: 'दर्द प्रबंधन और आराम वृद्धि', tokenCost: 2, free: false, audioEn: 'https://www.soundjay.com/buttons/sounds/button-1.mp3', audioHi: 'https://res.cloudinary.com/dtlitc3nv/video/upload/v1782919200/pain_s1_ddklop.mp3', image: '/images/content/pain/pain 1.jpg' },
      { id: 'f2', title: 'Session-2', description: 'लंबे समय से चले आ रहे दर्द के लिए मेडिटेशन', tokenCost: 2, free: false, audioEn: 'https://www.soundjay.com/buttons/sounds/button-1.mp3', audioHi: 'https://res.cloudinary.com/dtlitc3nv/video/upload/v1782919256/pain_s2_wfd9ey.mp3', image: '/images/content/pain/pain 2.jpg' },
      { id: 'f3', title: 'Session-3', description: 'Classic cinema overview and analysis.', tokenCost: 2, free: false, audioEn: 'https://www.soundjay.com/buttons/sounds/button-1.mp3', audioHi: 'https://www.soundjay.com/buttons/sounds/button-1.mp3', image: '/images/content/pain/pain 3.jpg' },
    ],
  },
  {
    id: 'Sleep Improvement / नींद में सुधार',
    name: 'Sleep Improvement / नींद में सुधार',
    description: ' ',
    icon: Sleep,
    image: '/images/categories/sleep-improvement.png',
    color: 'from-emerald-500 to-teal-400',
    video: 'https://www.w3schools.com/html/mov_bbb.mp4',
    itemCount: 42,
    items: [
      { id: 'b1', title: 'Session-1', description: 'गहन निद्रा', tokenCost: 2, free: false, audioEn: 'https://www.soundjay.com/buttons/sounds/button-1.mp3', audioHi: 'https://res.cloudinary.com/dtlitc3nv/video/upload/v1782919452/sleep_s1_lc4yje.mp3', image: '/images/content/sleep/sleep 1.jpg' },
      { id: 'b2', title: 'Session-2', description: 'क्या आपको रात भर नींद नहीं आती?', tokenCost: 2, free: false, audioEn: 'https://www.soundjay.com/buttons/sounds/button-1.mp3', audioHi: 'https://res.cloudinary.com/dtlitc3nv/video/upload/v1783080627/sleep_s2_ilwgg9.mp3', image: '/images/content/sleep/sleep 2.jpg' },
      { id: 'b3', title: 'Session-3', description: '5 short stories from emerging authors.', tokenCost: 2, free: false, audioEn: 'https://www.soundjay.com/buttons/sounds/button-1.mp3', audioHi: 'https://www.soundjay.com/buttons/sounds/button-1.mp3', image: '/images/content/sleep/sleep 3.jpg' },
    ],
  },
  {
    id: 'Emotional Healing / भावनात्मक हीलिंग',
    name: 'Emotional Healing / भावनात्मक हीलिंग',
    description: ' ',
    icon: Emotional,
    color: 'from-purple-500 to-violet-400',
    image: '/images/categories/emotional-healing.png',
    video: 'https://www.w3schools.com/html/mov_bbb.mp4',
    itemCount: 27,
    items: [
      { id: 'g1', title: 'Session-1', description: 'शिव और शक्ति हमारे जीवन में', tokenCost: 2, free: false, audioEn: 'https://www.soundjay.com/buttons/sounds/button-1.mp3', audioHi: 'https://res.cloudinary.com/dtlitc3nv/video/upload/v1783189926/emotional_1_penwpv.mp3', image: '/images/content/emotional/Emotional 1.jpg' },
      { id: 'g2', title: 'Session-2', description: 'Curated picks from the indie scene.', tokenCost: 2, free: false, audioEn: 'https://www.soundjay.com/buttons/sounds/button-1.mp3', audioHi: 'https://www.soundjay.com/buttons/sounds/button-1.mp3', image: '/images/content/emotional/Emotional 2.jpg' },
      { id: 'g3', title: 'Session-3', description: 'Improve aim, positioning and game sense.', tokenCost: 2, free: false, audioEn: 'https://www.soundjay.com/buttons/sounds/button-1.mp3', audioHi: 'https://www.soundjay.com/buttons/sounds/button-1.mp3', image: '/images/content/emotional/Emotional 3.jpg' },
    ],
  },
  {
    id: 'Fear & Phobia Release / डर और फोबिया से मुक्ति',
    name: 'Fear & Phobia Release / डर और फोबिया से मुक्ति',
    description: ' ',
    icon: Fear,
    color: 'from-red-500 to-pink-400',
    image: '/images/categories/fear-phobia-release.png',
    video: 'https://www.w3schools.com/html/mov_bbb.mp4',
    comingSoon: true,
    itemCount: 15,
    items: [
      { id: 'p1', title: 'Portrait Photography Guide', description: 'Lighting, posing and lens selection.', tokenCost: 2, free: false, audioEn: 'https://www.soundjay.com/buttons/sounds/button-1.mp3', audioHi: 'https://www.soundjay.com/buttons/sounds/button-1.mp3', image: 'https://images.unsplash.com/photo-1455390582262-044cdead277a?w=800' },
      { id: 'p2', title: 'Lightroom Preset Pack', description: '30 professional presets for every style.', tokenCost: 2, free: false, audioEn: 'https://www.soundjay.com/buttons/sounds/button-1.mp3', audioHi: 'https://www.soundjay.com/buttons/sounds/button-1.mp3', image: 'https://images.unsplash.com/photo-1455390582262-044cdead277a?w=800' },
      { id: 'p3', title: 'Phone Photography Tips', description: 'Shoot stunning photos on any smartphone.', tokenCost: 2, free: false, audioEn: 'https://www.soundjay.com/buttons/sounds/button-1.mp3', audioHi: 'https://www.soundjay.com/buttons/sounds/button-1.mp3', image: 'https://images.unsplash.com/photo-1455390582262-044cdead277a?w=800' },
      { id: 'p4', title: 'Street Photography 101', description: 'Capture authentic urban moments.', tokenCost: 2, free: false, audioEn: 'https://www.soundjay.com/buttons/sounds/button-1.mp3', audioHi: 'https://www.soundjay.com/buttons/sounds/button-1.mp3', image: 'https://images.unsplash.com/photo-1455390582262-044cdead277a?w=800' },
    ],
  },
  {
    id: 'Self-Confidence Boost / आत्म-विश्वास बढ़ाना',
    name: 'Self-Confidence Boost / आत्म-विश्वास बढ़ाना',
    description: ' ',
    icon: Self,
    color: 'from-pink-500 to-rose-400',
    image: '/images/categories/self-confidence-boost.png',
    video: 'https://www.w3schools.com/html/mov_bbb.mp4',
    comingSoon: true,
    itemCount: 18,
    items: [
      { id: 'm1', title: 'Chill Lo-Fi Pack Vol.1', description: '20 royalty-free lo-fi beats for focus.', tokenCost: 2, free: false, audioEn: 'https://www.soundjay.com/buttons/sounds/button-1.mp3', audioHi: 'https://www.soundjay.com/buttons/sounds/button-1.mp3', image: 'https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=800' },
      { id: 'm2', title: 'Guitar Chord Handbook', description: 'Complete guide to 100+ chord shapes.', tokenCost: 2, free: false, audioEn: 'https://www.soundjay.com/buttons/sounds/button-1.mp3', audioHi: 'https://www.soundjay.com/buttons/sounds/button-1.mp3', image: 'https://images.unsplash.com/photo-1510915361894-db8b60106cb1?w=800' },
      { id: 'm3', title: 'Music Theory Crash Course', description: 'Scales, intervals and harmony explained.', tokenCost: 2, free: false, audioEn: 'https://www.soundjay.com/buttons/sounds/button-1.mp3', audioHi: 'https://www.soundjay.com/buttons/sounds/button-1.mp3', image: 'https://images.unsplash.com/photo-1507838153414-b4b713384a76?w=800' },
      { id: 'm4', title: 'EDM Production Kit', description: 'Sample packs and FL Studio templates.', tokenCost: 2, free: false, audioEn: 'https://www.soundjay.com/buttons/sounds/button-1.mp3', audioHi: 'https://www.soundjay.com/buttons/sounds/button-1.mp3', image: 'https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?w=800' },
      { id: 'm5', title: 'Vocal Training 101', description: 'Breathing, pitch and performance tips.', tokenCost: 2, free: false, audioEn: 'https://www.soundjay.com/buttons/sounds/button-1.mp3', audioHi: 'https://www.soundjay.com/buttons/sounds/button-1.mp3', image: 'https://images.unsplash.com/photo-1516280440614-37939bbacd81?w=800' },
    ],
  },  
  {
    id: 'Smoking  Tobacco De-addiction  धूम्रपान  तंबाकू की लत से छुटकारा',
    name: 'Smoking  Tobacco De-addiction  धूम्रपान  तंबाकू की लत से छुटकारा',
    description: ' ',
    icon: Smoking,
    color: 'from-amber-500 to-yellow-400',
    image: '/images/categories/smoking-tobacco-deaddiction.png',
    video: 'https://www.w3schools.com/html/mov_bbb.mp4',
    comingSoon: true,
    itemCount: 22,
    items: [
      { id: 'tr1', title: 'Budget Travel Europe', description: 'Explore 10 countries under ₹50,000.', tokenCost: 3, free: false, imagfree: false, audioEn: 'https://www.soundjay.com/buttons/sounds/button-1.mp3', audioHi: 'https://www.soundjay.com/buttons/sounds/button-1.mp3', image: 'https://images.unsplash.com/photo-1455390582262-044cdead277a?w=800' },
      { id: 'tr2', title: 'Solo Travel Safety Guide', description: 'Essential tips for travelling alone.', tokenCost: 0, free: true, audioEn: 'https://www.soundjay.com/buttons/sounds/button-1.mp3', audioHi: 'https://www.soundjay.com/buttons/sounds/button-1.mp3', image: 'https://images.unsplash.com/photo-1455390582262-044cdead277a?w=800' },
      { id: 'tr3', title: 'Hidden Gems of India', description: 'Off-beat destinations across India.', tokenCost: 4, free: false, audioEn: 'https://www.soundjay.com/buttons/sounds/button-1.mp3', audioHi: 'https://www.soundjay.com/buttons/sounds/button-1.mp3', image: 'https://images.unsplash.com/photo-1455390582262-044cdead277a?w=800' },
      { id: 'tr4', title: 'Travel Photography Tips', description: 'Document your journey beautifully.', tokenCost: 3, free: false, audioEn: 'https://www.soundjay.com/buttons/sounds/button-1.mp3', audioHi: 'https://www.soundjay.com/buttons/sounds/button-1.mp3', image: 'https://images.unsplash.com/photo-1455390582262-044cdead277a?w=800' },
    ],
  },
  {
    id: 'Stress Management / तनाव का प्रबंधन',
    name: 'Stress Management / तनाव का प्रबंधन',
    description: ' ',
    icon: Stress,
    color: 'from-red-500 to-rose-400',
    image: '/images/categories/stress-management.png',
    video: 'https://www.w3schools.com/html/mov_bbb.mp4',
    comingSoon: true,
    itemCount: 33,
    items: [
      { id: 'h1', title: '30-Day Yoga Plan', description: 'Daily yoga routines for all levels.', tokenCost: 5, free: false, audioEn: 'https://www.soundjay.com/buttons/sounds/button-1.mp3', audioHi: 'https://www.soundjay.com/buttons/sounds/button-1.mp3', image: 'https://images.unsplash.com/photo-1455390582262-044cdead277a?w=800' },
      { id: 'h2', title: 'Nutrition Basics', description: 'Understand macros, micros and meal timing.', tokenCost: 0, free: true, audioEn: 'https://www.soundjay.com/buttons/sounds/button-1.mp3', audioHi: 'https://www.soundjay.com/buttons/sounds/button-1.mp3', image: 'https://images.unsplash.com/photo-1455390582262-044cdead277a?w=800' },
      { id: 'h3', title: 'Mental Health Workbook', description: 'Exercises for anxiety, stress and focus.', tokenCost: 4, free: false, audioEn: 'https://www.soundjay.com/buttons/sounds/button-1.mp3', audioHi: 'https://www.soundjay.com/buttons/sounds/button-1.mp3', image: 'https://images.unsplash.com/photo-1455390582262-044cdead277a?w=800' },
      { id: 'h4', title: 'Home Workout Program', description: 'Full-body training with no equipment.', tokenCost: 3, free: false, audioEn: 'https://www.soundjay.com/buttons/sounds/button-1.mp3', audioHi: 'https://www.soundjay.com/buttons/sounds/button-1.mp3', image: 'https://images.unsplash.com/photo-1455390582262-044cdead277a?w=800' },
    ],
  },
  {
    id: 'Weight Loss Mind Programming / वज़न घटाने के लिए माइंड प्रोग्रामिंग',
    name: 'Weight Loss Mind Programming / वज़न घटाने के लिए माइंड प्रोग्रामिंग',
    description: ' ',
    icon: Weight,
    color: 'from-amber-500 to-yellow-400',
    image: '/images/categories/weight-loss-mind-programming.png',
    video: 'https://www.w3schools.com/html/mov_bbb.mp4',
    comingSoon: true,
    itemCount: 11,
    items: [
      { id: 'sh1', title: 'Best Budget Laptops 2025', description: 'Top picks under ₹50,000.', tokenCost: 2, free: false, audioEn: 'https://www.soundjay.com/buttons/sounds/button-1.mp3', audioHi: 'https://www.soundjay.com/buttons/sounds/button-1.mp3', image: 'https://images.unsplash.com/photo-1455390582262-044cdead277a?w=800' },
      { id: 'sh2', title: 'Smartphone Buying Guide', description: 'Compare specs and find your match.', tokenCost: 0, free: true, audioEn: 'https://www.soundjay.com/buttons/sounds/button-1.mp3', audioHi: 'https://www.soundjay.com/buttons/sounds/button-1.mp3', image: 'https://images.unsplash.com/photo-1455390582262-044cdead277a?w=800' },
      { id: 'sh3', title: 'Home Office Setup Guide', description: 'Ergonomic gear for remote work.', tokenCost: 3, free: false, audioEn: 'https://www.soundjay.com/buttons/sounds/button-1.mp3', audioHi: 'https://www.soundjay.com/buttons/sounds/button-1.mp3', image: 'https://images.unsplash.com/photo-1455390582262-044cdead277a?w=800' },
    ],
  },
  
  
]