import {
  Brain as Anxiety,
  Sparkles as abundance,
  HeartPulse as Pain,
  Moon as Sleep,
  Heart as Emotional,
  ShieldAlert as wisdom,
  BrainCircuit as Overthinking,
  Cigarette as Smoking,
  Activity as Blood,
  Scale as Weight,
} from 'lucide-react'

export const CATEGORIES = [
  {
    id: 'Anxiety Relief / चिंता से राहत',
    name: 'Anxiety Relief / चिंता से राहत',
    description: ' ',
    icon: Anxiety,
    color: 'from-blue-500 to-cyan-400',
    image: '/images/categories/anxiety-relief.png',
    video: 'https://www.w3schools.com/html/mov_bbb.mp4',
     
    itemCount: 24,
    items: [
      { id: 't1', title: 'Session-1', description: 'गहन विश्राम और अंतरिक्ष सहजता का हिप्नोथेरेपी  सेशन', tokenCost: 2, free: false, audioEn: 'https://www.soundjay.com/buttons/sounds/button-1.mp3', audioHi: 'https://res.cloudinary.com/dtlitc3nv/video/upload/v1782919318/relax_s1_ziryk9.mp3', image: '/images/content/anxiety/anxiety 1.jpg' },
      { id: 't2', title: 'Session-2', description: 'तूफ़ान के बाद का आकाश" और "पहाड़ों की नदी', tokenCost: 2, free: false, audioEn: 'https://www.soundjay.com/buttons/sounds/button-1.mp3', audioHi: 'https://res.cloudinary.com/dtlitc3nv/video/upload/v1783363259/relax_s2_wclenw.mp3', image: '/images/content/anxiety/anxiety2.jpg' },
    ],
  },
  {
    id: 'Overthinking Control / ज़्यादा सोचने की आदत पर नियंत्रण',
    name: 'Overthinking Control / ज़्यादा सोचने की आदत पर नियंत्रण',
    description: ' ',
    icon: Overthinking,
    color: 'from-indigo-500 to-purple-400',
    image: '/images/categories/overthinking-control.png',
    video: 'https://www.w3schools.com/html/mov_bbb.mp4',
    itemCount: 20,
    items: [
      { id: 'free-meditation-1', title: 'Meditation & Deep Relaxation / ध्यान और गहन विश्राम', description: 'अशांत विचारों को शांत करने और मन को स्थिर करने का 100% निःशुल्क हिप्नोथेरेपी सेशन', tokenCost: 0, free: true, audioEn: 'https://res.cloudinary.com/dtlitc3nv/video/upload/v1782998298/meditation_1_oevnh7.mp3', audioHi: 'https://res.cloudinary.com/dtlitc3nv/video/upload/v1782998298/meditation_1_oevnh7.mp3', image: '/images/free/meditation.jpg' },
      { id: 'd1', title: 'Session-1', description: 'आंतरिक शांति और चिंता रहित रहने के लिए', tokenCost: 2, free: false, audioEn: 'https://www.soundjay.com/buttons/sounds/button-1.mp3', audioHi: 'https://res.cloudinary.com/dtlitc3nv/video/upload/v1782918954/overthinking_1_qw6nhl.mp3', image: '/images/content/overthinking/overthinking 1.jpg' },
      { id: 'd2', title: 'Session-2', description: 'शून्य से शून्य की ओर', tokenCost: 2, free: false, audioEn: 'https://www.soundjay.com/buttons/sounds/button-1.mp3', audioHi: 'https://res.cloudinary.com/dtlitc3nv/video/upload/v1783328382/overthinking_2_gzqt2c.mp3', image: '/images/content/overthinking/overthinking 2.jpg' },
    ],
  },
  {
    id: 'Pain Management / दर्द का प्रबंधन',
    name: 'Pain Management / दर्द का प्रबंधन',
    description: ' ',
    icon: Pain,
    color: 'from-yellow-500 to-orange-400',
    image: '/images/categories/pain-management.png',
    video: 'https://www.w3schools.com/html/mov_bbb.mp4',
    itemCount: 31,
    items: [
      { id: 'f1', title: 'Session-1 ', description: 'दर्द प्रबंधन और आराम वृद्धि', tokenCost: 2, free: false, audioEn: 'https://www.soundjay.com/buttons/sounds/button-1.mp3', audioHi: 'https://res.cloudinary.com/dtlitc3nv/video/upload/v1782919200/pain_s1_ddklop.mp3', image: '/images/content/pain/pain 1.jpg' },
      { id: 'f2', title: 'Session-2', description: 'लंबे समय से चले आ रहे दर्द के लिए मेडिटेशन', tokenCost: 2, free: false, audioEn: 'https://www.soundjay.com/buttons/sounds/button-1.mp3', audioHi: 'https://res.cloudinary.com/dtlitc3nv/video/upload/v1782919256/pain_s2_wfd9ey.mp3', image: '/images/content/pain/pain 2.jpg' },
      { id: 'f3', title: 'Session-3', description: 'लंबे समय से चले आ रहे दर्द से राहत और गाइडेड सोमैटिक हीलिंग', tokenCost: 2, free: false, audioEn: 'https://www.soundjay.com/buttons/sounds/button-1.mp3', audioHi: 'https://res.cloudinary.com/dtlitc3nv/video/upload/v1783362809/pain_s3_ggecj4.mp3', image: '/images/content/pain/pain 3.jpg' },
      { id: 'f4', title: 'Session-4', description: 'सूर्य की गर्माहट और पिघलते मक्खन', tokenCost: 2, free: false, audioEn: 'https://www.soundjay.com/buttons/sounds/button-1.mp3', audioHi: 'https://res.cloudinary.com/dtlitc3nv/video/upload/v1783861145/pain_s4_sewfdl.mp3', image: '/images/content/pain/pain 4.jpg' },
      { id: 'f5', title: 'To relieve stiffness and tightness in the nerves of the lower back and spine.', description: 'कमर और रीढ़ की नसों में जकड़न, अकड़न को खोलने के लिए', tokenCost: 2, free: false, audioEn: 'https://www.soundjay.com/buttons/sounds/button-1.mp3', audioHi: 'https://res.cloudinary.com/dtlitc3nv/video/upload/v1787665180/lower_back_side_pain_ujpcw0.mp3', image: '/images/content/pain/pain-5.png' },
    ],
  },
  {
    id: 'Sleep Improvement / नींद में सुधार',
    name: 'Sleep Improvement / नींद में सुधार',
    description: ' ',
    icon: Sleep,
    image: '/images/categories/sleep-improvement.png',
    color: 'from-emerald-500 to-teal-400',
    video: 'https://www.w3schools.com/html/mov_bbb.mp4',
    itemCount: 42,
    items: [
      { id: 'b1', title: 'Session-1', description: 'गहन निद्रा', tokenCost: 2, free: false, audioEn: 'https://www.soundjay.com/buttons/sounds/button-1.mp3', audioHi: 'https://res.cloudinary.com/dtlitc3nv/video/upload/v1782919452/sleep_s1_lc4yje.mp3', image: '/images/content/sleep/sleep 1.jpg' },
      { id: 'b2', title: 'Session-2', description: 'क्या आपको रात भर नींद नहीं आती?', tokenCost: 2, free: false, audioEn: 'https://www.soundjay.com/buttons/sounds/button-1.mp3', audioHi: 'https://res.cloudinary.com/dtlitc3nv/video/upload/v1783080627/sleep_s2_ilwgg9.mp3', image: '/images/content/sleep/sleep 2.jpg' },
    ],
  },
  {
    id: 'Emotional Healing / भावनात्मक हीलिंग',
    name: 'Emotional Healing / भावनात्मक हीलिंग',
    description: ' ',
    icon: Emotional,
    color: 'from-purple-500 to-violet-400',
    image: '/images/categories/emotional-healing.png',
    video: 'https://www.w3schools.com/html/mov_bbb.mp4',
    itemCount: 27,
    items: [
      { id: 'g1', title: 'Session-1', description: 'शिव और शक्ति हमारे जीवन में', tokenCost: 2, free: false, audioEn: 'https://www.soundjay.com/buttons/sounds/button-1.mp3', audioHi: 'https://res.cloudinary.com/dtlitc3nv/video/upload/v1783189926/emotional_1_penwpv.mp3', image: '/images/content/emotional/Emotional 1.jpg' },
      { id: 'g2', title: 'Session-2', description: 'दिव्य हीलिंग एवं कृतज्ञता हिप्नोथेरेपी / गाइडेड मेडिटेशन', tokenCost: 2, free: false, audioEn: 'https://www.soundjay.com/buttons/sounds/button-1.mp3', audioHi: 'https://res.cloudinary.com/dtlitc3nv/video/upload/v1783861167/emotional_2_qpbn6b.mp3', image: '/images/content/emotional/Emotional 2.jpg' },
      { id: 'g3', title: 'Session-3', description: 'बेहतर ज़िंदगी के लिए सकारात्मक सुझाव', tokenCost: 2, free: false, audioEn: 'https://www.soundjay.com/buttons/sounds/button-1.mp3', audioHi: 'https://res.cloudinary.com/dtlitc3nv/video/upload/v1786043677/emotional_3_qqtxpt.mp3', image: '/images/content/emotional/Emotional 3.jpg' },
    ],
  },
  {
    id: 'Weight Loss Mind Programming / वज़न घटाने के लिए माइंड प्रोग्रामिंग',
    name: 'Weight Loss Mind Programming / वज़न घटाने के लिए माइंड प्रोग्रामिंग',
    description: ' ',
    icon: Weight,
    color: 'from-amber-500 to-yellow-400',
    image: '/images/categories/weight-loss-mind-programming.png',
    video: 'https://www.w3schools.com/html/mov_bbb.mp4',
    comingSoon: false,
    itemCount: 11,
    items: [
      { id: 'sh1', title: 'वजन कम करने के लिए', description: 'वजन कम करने के लिए मन और आदतों में सकारात्मक बदलाव लाने वाली निर्देशित हिप्नोथेरेपी।', tokenCost: 2, free: false, audioEn: 'https://www.soundjay.com/buttons/sounds/button-1.mp3', audioHi: 'https://res.cloudinary.com/dtlitc3nv/video/upload/v1785428873/weight_loss_meipdk.mp3', image: '/images/content/weight loss/weight.png' },
    ],
  },
  {
    id: 'Blood pressure control/ रक्तचाप नियंत्रण',
    name: 'Blood pressure control/ रक्तचाप नियंत्रण',
    description: ' ',
    icon: Blood,
    color: 'from-red-500 to-rose-400',
    image: '/images/categories/stress-management.png',
    video: 'https://www.w3schools.com/html/mov_bbb.mp4',
    comingSoon: false,
    itemCount: 33,
    items: [
      { id: 'h1', title: 'रक्तचाप नियंत्रण', description: 'तनाव कम करने और गहरी शांति को बढ़ावा देकर स्वस्थ रक्तचाप बनाए रखने में सहायक निर्देशित हिप्नोथेरेपी।', tokenCost: 2, free: false, audioEn: 'https://www.soundjay.com/buttons/sounds/button-1.mp3', audioHi: 'https://res.cloudinary.com/dtlitc3nv/video/upload/v1785435567/bp_qw8omv.mp3', image: '/images/content/bp/bp.png'  },
    ],
  },
  {
    id: 'Inner Wisdom / आंतरिक ज्ञान',
    name: 'Inner Wisdom / आंतरिक ज्ञान',
    description: ' ',
    icon: wisdom,
    color: 'from-red-500 to-pink-400',
    image: '/images/categories/inner-wisdom.jpg',
    video: 'https://www.w3schools.com/html/mov_bbb.mp4',
    comingSoon: false,
    itemCount: 15,
    items: [
      { id: 'p1', title: 'अनंत ज्ञान की लाइब्रेरी', description: 'अनंत ज्ञान की लाइब्रेरी', tokenCost: 2, free: false, audioEn: 'https://www.soundjay.com/buttons/sounds/button-1.mp3', audioHi: 'https://res.cloudinary.com/dtlitc3nv/video/upload/v1785829454/inner_wisdom_f2x7ub.mp3', image: '/images/content/wisdom/wisdom.png' },
    ],
  },
  {
    id: 'abundance / समृद्धि प्रचुरता',
    name: 'abundance / समृद्धि प्रचुरता',
    description: ' ',
    icon: abundance,
    color: 'from-pink-500 to-rose-400',
    image: '/images/categories/abundance.png',
    video: 'https://www.w3schools.com/html/mov_bbb.mp4',
    comingSoon: false,
    itemCount: 18,
    items: [
      { id: 'm1', title: 'आर्थिक समृद्धि पाएं', description: 'आर्थिक समृद्धि पाएं', tokenCost: 2, free: false, audioEn: 'https://www.soundjay.com/buttons/sounds/button-1.mp3', audioHi: 'https://res.cloudinary.com/dtlitc3nv/video/upload/v1785854693/abundance_lvxuxc.mp3', image: '/images/content/abundance/abundance.png' },
    ]
  },  
  {
    id: 'Smoking  Tobacco De-addiction  धूम्रपान  तंबाकू की लत से छुटकारा',
    name: 'Smoking  Tobacco De-addiction  धूम्रपान  तंबाकू की लत से छुटकारा',
    description: ' ',
    icon: Smoking,
    color: 'from-amber-500 to-yellow-400',
    image: '/images/categories/smoking-tobacco-deaddiction.png',
    video: 'https://www.w3schools.com/html/mov_bbb.mp4',
    comingSoon: true,
    itemCount: 22,
    items: [
      { id: 'tr1', title: 'Budget Travel Europe', description: 'Explore 10 countries under ₹50,000.', tokenCost: 3, free: false, imagfree: false, audioEn: 'https://www.soundjay.com/buttons/sounds/button-1.mp3', audioHi: 'https://www.soundjay.com/buttons/sounds/button-1.mp3', image: 'https://images.unsplash.com/photo-1455390582262-044cdead277a?w=800' },
      { id: 'tr2', title: 'Solo Travel Safety Guide', description: 'Essential tips for travelling alone.', tokenCost: 0, free: true, audioEn: 'https://www.soundjay.com/buttons/sounds/button-1.mp3', audioHi: 'https://www.soundjay.com/buttons/sounds/button-1.mp3', image: 'https://images.unsplash.com/photo-1455390582262-044cdead277a?w=800' },
      { id: 'tr3', title: 'Hidden Gems of India', description: 'Off-beat destinations across India.', tokenCost: 4, free: false, audioEn: 'https://www.soundjay.com/buttons/sounds/button-1.mp3', audioHi: 'https://www.soundjay.com/buttons/sounds/button-1.mp3', image: 'https://images.unsplash.com/photo-1455390582262-044cdead277a?w=800' },
      { id: 'tr4', title: 'Travel Photography Tips', description: 'Document your journey beautifully.', tokenCost: 3, free: false, audioEn: 'https://www.soundjay.com/buttons/sounds/button-1.mp3', audioHi: 'https://www.soundjay.com/buttons/sounds/button-1.mp3', image: 'https://images.unsplash.com/photo-1455390582262-044cdead277a?w=800' },
    ],
  },
  
]